name: BlockChanger
main: me.tijela.BlockChanger.BlockChanger
author: Tijela_Quebrada
version: 1.1
commands:
  BlockChanger:
    description: Makes all blocks damaged set to wool.
    permissions: BlockChanger.use
    usage: /<command>
